Update file Jenkinsfile.nightly

diff --git a/Jenkinsfile.nightly b/Jenkinsfile.nightly
--- a/Jenkinsfile.nightly
+++ b/Jenkinsfile.nightly
@@ -203,94 +203,94 @@ spec:
                 }
             }
             
-            stage ('checkmarx-scans') {
-                gitlabCommitStatus(name: "checkmarx-scan-test", connection: gitLabConnection('git-lab-master')) {
-                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-                        withCredentials([usernamePassword(credentialsId: 'checkmarx-ac-account', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
-                            withEnv([
-                            "CHECKMARX_USERNAME=${USERNAME}",
-                            "CHECKMARX_PASSWORD=${PASSWORD}",
-                            "CX_TEAM=CxServer/SP/Company/TLT",
-                            "CX_PROJECT=TAO-TF2",
-                            "CHECKMARX_BASE_URL=https://checkmarx.nvidia.com",
-                            "CHECKMARX_VERSION=9.0",
-                            "CHECKMARX_SETTINGS_OVERRIDE=false",
-                            "CHECKMARX_CONFIGURATION=Default Configuration",
-                            "CHECKMARX_SCAN_PRESET=Checkmarx Default",
-                            "CX_FLOW_BREAK_BUILD=true",
-                            "CX_FLOW_ZIP_EXCLUDE=''",
-                            "CX_PARAMS=''"
-                            ]){
-                                docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
-                                    def img = 'pstooling/images/base-images/debian:cxflow-latest-prodsec-stable'
-                                    docker.image(img).inside("--entrypoint=''") {
-                                        sh '/app/check_variables.sh jenkins'
-                                        sh """
-                                        java -jar /app/cx-flow.jar \
-                                        --scan \
-                                        --bug-tracker="Csv" \
-                                        --csv.file-name-format="[TEAM]-[PROJECT]-[TIME].csv" \
-                                        --csv.include-headers="true" \
-                                        --csv.data-folder="checkmarx" \
-                                        --app="${CX_PROJECT}" \
-                                        --cx-team="${CX_TEAM}" \
-                                        --cx-project="${CX_PROJECT}" \
-                                        --spring.profiles.active="sast" \
-                                        --f=. \
-                                        ${CX_PARAMS}
-                                        """
-                                        sh '/app/check_timeout.sh'
-                                    }
-                                }
-                            }
-                        }
-                    }
-                }
-            }
+            // stage ('checkmarx-scans') {
+            //     gitlabCommitStatus(name: "checkmarx-scan-test", connection: gitLabConnection('git-lab-master')) {
+            //         catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+            //             withCredentials([usernamePassword(credentialsId: 'checkmarx-ac-account', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
+            //                 withEnv([
+            //                 "CHECKMARX_USERNAME=${USERNAME}",
+            //                 "CHECKMARX_PASSWORD=${PASSWORD}",
+            //                 "CX_TEAM=CxServer/SP/Company/TLT",
+            //                 "CX_PROJECT=TAO-TF2",
+            //                 "CHECKMARX_BASE_URL=https://checkmarx.nvidia.com",
+            //                 "CHECKMARX_VERSION=9.0",
+            //                 "CHECKMARX_SETTINGS_OVERRIDE=false",
+            //                 "CHECKMARX_CONFIGURATION=Default Configuration",
+            //                 "CHECKMARX_SCAN_PRESET=Checkmarx Default",
+            //                 "CX_FLOW_BREAK_BUILD=true",
+            //                 "CX_FLOW_ZIP_EXCLUDE=''",
+            //                 "CX_PARAMS=''"
+            //                 ]){
+            //                     docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
+            //                         def img = 'pstooling/images/base-images/debian:cxflow-latest-prodsec-stable'
+            //                         docker.image(img).inside("--entrypoint=''") {
+            //                             sh '/app/check_variables.sh jenkins'
+            //                             sh """
+            //                             java -jar /app/cx-flow.jar \
+            //                             --scan \
+            //                             --bug-tracker="Csv" \
+            //                             --csv.file-name-format="[TEAM]-[PROJECT]-[TIME].csv" \
+            //                             --csv.include-headers="true" \
+            //                             --csv.data-folder="checkmarx" \
+            //                             --app="${CX_PROJECT}" \
+            //                             --cx-team="${CX_TEAM}" \
+            //                             --cx-project="${CX_PROJECT}" \
+            //                             --spring.profiles.active="sast" \
+            //                             --f=. \
+            //                             ${CX_PARAMS}
+            //                             """
+            //                             sh '/app/check_timeout.sh'
+            //                         }
+            //                     }
+            //                 }
+            //             }
+            //         }
+            //     }
+            // }
 
-            stage ('pulse_oss_scan') {
-                gitlabCommitStatus(name: "pulse_oss_scan", connection: gitLabConnection('git-lab-master')) {
-                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-                        withEnv(["TAO_VERSION=5.2.0", "IMAGE_NAME=nvcr.io/nvstaging/tao/tao-toolkit-tf2", "TF_VERSION=2.9.1", "CUDA_VERSION=11.8"]){
-                            docker.withRegistry('https://nvcr.io', 'NGC_API_KEY'){
-                                docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
-                                    def NSPECT_ID="NSPECT-76DN-OP7I"
-                                    def SSA_TOKEN=getPulseToken()
-                                    def CONTAINER_TAG="${IMAGE_NAME}:v${TAO_VERSION}-tf${TF_VERSION}-${BUILD_NUMBER}-dev-cuda${CUDA_VERSION}"
-                                    def CONTAINER_ARCHIVE="container_image.tar"
-                                    def CONTAINER_SCAN_POLICY="policy.json"
+            // stage ('pulse_oss_scan') {
+            //     gitlabCommitStatus(name: "pulse_oss_scan", connection: gitLabConnection('git-lab-master')) {
+            //         catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+            //             withEnv(["TAO_VERSION=5.2.0", "IMAGE_NAME=nvcr.io/nvstaging/tao/tao-toolkit-tf2", "TF_VERSION=2.9.1", "CUDA_VERSION=11.8"]){
+            //                 docker.withRegistry('https://nvcr.io', 'NGC_API_KEY'){
+            //                     docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
+            //                         def NSPECT_ID="NSPECT-76DN-OP7I"
+            //                         def SSA_TOKEN=getPulseToken()
+            //                         def CONTAINER_TAG="${IMAGE_NAME}:v${TAO_VERSION}-tf${TF_VERSION}-${BUILD_NUMBER}-dev-cuda${CUDA_VERSION}"
+            //                         def CONTAINER_ARCHIVE="container_image.tar"
+            //                         def CONTAINER_SCAN_POLICY="policy.json"
 
-                                    try {
-                                        sh """
-                                        docker save ${CONTAINER_TAG} > ${CONTAINER_ARCHIVE}
-                                        wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/policy.json
-                                        ls -al
-                                        docker run -v .:/dist -w /dist gitlab-master.nvidia.com:5005/pstooling/pulse-group/pulse-container-scanner/pulse-cli:stable /bin/sh -c "pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN scan -i $CONTAINER_ARCHIVE -p $CONTAINER_SCAN_POLICY -o || true"
-                                        """
-                                    } catch (Exception e) {
-                                        echo "Continuing with the pipeline..."
-                                        echo "An error occurred: ${e.getMessage()}"
-                                    }
+            //                         try {
+            //                             sh """
+            //                             docker save ${CONTAINER_TAG} > ${CONTAINER_ARCHIVE}
+            //                             wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/policy.json
+            //                             ls -al
+            //                             docker run -v .:/dist -w /dist gitlab-master.nvidia.com:5005/pstooling/pulse-group/pulse-container-scanner/pulse-cli:stable /bin/sh -c "pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN scan -i $CONTAINER_ARCHIVE -p $CONTAINER_SCAN_POLICY -o || true"
+            //                             """
+            //                         } catch (Exception e) {
+            //                             echo "Continuing with the pipeline..."
+            //                             echo "An error occurred: ${e.getMessage()}"
+            //                         }
 
-                                    execution_script = '''
-                                        wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/vulnerabilities_validation.py
-                                        ls -al
-                                        python3 -m pip install pandas
-                                        python3 vulnerabilities_validation.py
-                                    '''
-                                    def shellOutput = sh(script: execution_script, returnStdout: true).toString()
-                                    echo shellOutput
-                                    if (shellOutput.contains("Scan result : FAIL")) {
-                                        error("Unsuccessful Execution . . .")
-                                    }
+            //                         execution_script = '''
+            //                             wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/vulnerabilities_validation.py
+            //                             ls -al
+            //                             python3 -m pip install pandas
+            //                             python3 vulnerabilities_validation.py
+            //                         '''
+            //                         def shellOutput = sh(script: execution_script, returnStdout: true).toString()
+            //                         echo shellOutput
+            //                         if (shellOutput.contains("Scan result : FAIL")) {
+            //                             error("Unsuccessful Execution . . .")
+            //                         }
 
-                                    sh "rm -rf ${CONTAINER_ARCHIVE}"
-                                }
-                            }
-                        }
-                    }
-                }
-            }
+            //                         sh "rm -rf ${CONTAINER_ARCHIVE}"
+            //                     }
+            //                 }
+            //             }
+            //         }
+            //     }
+            // }
 
             stage ('cleanup_scratch_space_in_dind') {
                 sh 'umount /home/scratch.metropolis2'
