Update 2 files
- /Jenkinsfile.nightly
- /Jenkinsfile.release

diff --git a/Jenkinsfile.nightly b/Jenkinsfile.nightly
--- a/Jenkinsfile.nightly
+++ b/Jenkinsfile.nightly
@@ -83,6 +83,7 @@ spec:
                     command_env = pythonpath_env + ' ' + ci_path_env
                 }
             }
+
             stage ('setup_scratch_space') {
                 sh 'apt-get update'
                 sh 'apt-get install cifs-utils -y'
@@ -95,14 +96,14 @@ spec:
                 sh 'ls -l /home/scratch.metropolis2'
             }
 
-            // stage ("functional_tests"){
-            //     gitlabCommitStatus(name: "functional_tests", connection: gitLabConnection('git-lab-master')) {
-            //         println "skipping functional_tests for now .."
-            //         sh "pip install pytest-cov"
-            //         sh "${command_env} python ci/run_functional_tests.py --cov=nvidia_tao_tf2 --cov-report="
-            //         sh "cp .coverage /home/scratch.metropolis2/users/release_pipeline_files/coverage_reports/functional_test/.coverage.fn_tf2"
-            //     }
-            // }
+            stage ("functional_tests"){
+                gitlabCommitStatus(name: "functional_tests", connection: gitLabConnection('git-lab-master')) {
+                    println "skipping functional_tests for now .."
+                    sh "pip install pytest-cov"
+                    sh "${command_env} python ci/run_functional_tests.py --cov=nvidia_tao_tf2 --cov-report="
+                    sh "cp .coverage /home/scratch.metropolis2/users/release_pipeline_files/coverage_reports/functional_test/.coverage.fn_tf2"
+                }
+            }
 
             stage ('build_wheel') {
                 gitlabCommitStatus(name: "build_wheel", connection: gitLabConnection('git-lab-master')) {
@@ -122,29 +123,29 @@ spec:
                 }
             }
 
-            // stage ('wheel_publish') {
-            //     gitlabCommitStatus(name: "wheel_publish", connection: gitLabConnection('git-lab-master')) {
-            //         // install jfrog first
-            //         sh "bash ${WORKSPACE}/docker/install_jfrog.sh"
-            //         sh "ls -al dist/"
-            //         def TAO_WHEEL_VERSION="4.0.0"
-            //         def BUILD_TYPE="dev"
-            //         def VER="${TAO_WHEEL_VERSION}.${BUILD_NUMBER}.${BUILD_TYPE}0"
-            //         def PYTHON_VER="py3-none"
-            //         def ARCH="any"
-            //         def SRC="dist/nvidia_tao_tf2-${VER}-${PYTHON_VER}-${ARCH}.whl"
-            //         def TARGET="sw-tao-pypi-local/nvidia-tao-tf2-nightly/${VER}/"
-            //         def PROP="component_name=nvidia-tao-tf2;arch=x86_64;os=linux;build_source=None;version=${VER};branch=main;release_approver=vpraveen"
-            //         withCredentials([usernamePassword(credentialsId: 'tao-artifactory-tkn', passwordVariable: 'JFROG_PASSWORD', usernameVariable: 'JFROG_USERNAME')]) {
-            //             sh "jfrog rt u --url=https://urm.nvidia.com/artifactory/ --user=${JFROG_USERNAME} --apikey=${JFROG_PASSWORD} --target-props '${PROP}' ${SRC} ${TARGET}"
-            //         }
+            stage ('wheel_publish') {
+                gitlabCommitStatus(name: "wheel_publish", connection: gitLabConnection('git-lab-master')) {
+                    // install jfrog first
+                    sh "bash ${WORKSPACE}/docker/install_jfrog.sh"
+                    sh "ls -al dist/"
+                    def TAO_WHEEL_VERSION="4.0.0"
+                    def BUILD_TYPE="dev"
+                    def VER="${TAO_WHEEL_VERSION}.${BUILD_NUMBER}.${BUILD_TYPE}0"
+                    def PYTHON_VER="py3-none"
+                    def ARCH="any"
+                    def SRC="dist/nvidia_tao_tf2-${VER}-${PYTHON_VER}-${ARCH}.whl"
+                    def TARGET="sw-tao-pypi-local/nvidia-tao-tf2-nightly/${VER}/"
+                    def PROP="component_name=nvidia-tao-tf2;arch=x86_64;os=linux;build_source=None;version=${VER};branch=main;release_approver=vpraveen"
+                    withCredentials([usernamePassword(credentialsId: 'tao-artifactory-tkn', passwordVariable: 'JFROG_PASSWORD', usernameVariable: 'JFROG_USERNAME')]) {
+                        sh "jfrog rt u --url=https://urm.nvidia.com/artifactory/ --user=${JFROG_USERNAME} --apikey=${JFROG_PASSWORD} --target-props '${PROP}' ${SRC} ${TARGET}"
+                    }
 
-            //         def append_string="tf2_wheel: nvidia_tao_tf2-${VER}-${PYTHON_VER}-${ARCH}.whl"
-            //         def config_file_path = "/home/scratch.metropolis2/users/release_pipeline_files/release_items.yml"
-            //         sh "python3 ci/update_release_config.py ${config_file_path} '${append_string}'"
-            //         sh "cat /home/scratch.metropolis2/users/release_pipeline_files/release_items.yml"
-            //     }
-            // }
+                    def append_string="tf2_wheel: nvidia_tao_tf2-${VER}-${PYTHON_VER}-${ARCH}.whl"
+                    def config_file_path = "/home/scratch.metropolis2/users/release_pipeline_files/release_items.yml"
+                    sh "python3 ci/update_release_config.py ${config_file_path} '${append_string}'"
+                    sh "cat /home/scratch.metropolis2/users/release_pipeline_files/release_items.yml"
+                }
+            }
 
             stage ('cleanup_scratch_space') {
                 sh 'umount /home/scratch.metropolis2'
@@ -219,94 +220,92 @@ spec:
                 }
             }
             
-            // stage ('checkmarx-scans') {
-            //     gitlabCommitStatus(name: "checkmarx-scan-test", connection: gitLabConnection('git-lab-master')) {
-            //         withCredentials([usernamePassword(credentialsId: 'checkmarx-ac-account', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
-            //             withEnv([
-            //             "CHECKMARX_USERNAME=${USERNAME}",
-            //             "CHECKMARX_PASSWORD=${PASSWORD}",
-            //             "CX_TEAM=CxServer/SP/Company/TLT",
-            //             "CX_PROJECT=TAO-TF2",
-            //             "CHECKMARX_BASE_URL=https://checkmarx.nvidia.com",
-            //             "CHECKMARX_VERSION=9.0",
-            //             "CHECKMARX_SETTINGS_OVERRIDE=false",
-            //             "CHECKMARX_CONFIGURATION=Default Configuration",
-            //             "CHECKMARX_SCAN_PRESET=Checkmarx Default",
-            //             "CX_FLOW_BREAK_BUILD=true",
-            //             "CX_FLOW_ZIP_EXCLUDE=''",
-            //             "CX_PARAMS=''"
-            //             ]){
-            //                 docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
-            //                     def img = 'pstooling/images/base-images/debian:cxflow-latest-prodsec-stable'
-            //                     docker.image(img).inside("--entrypoint=''") {
-            //                         sh '/app/check_variables.sh jenkins'
-            //                         sh """
-            //                         java -jar /app/cx-flow.jar \
-            //                         --scan \
-            //                         --bug-tracker="Csv" \
-            //                         --csv.file-name-format="[TEAM]-[PROJECT]-[TIME].csv" \
-            //                         --csv.include-headers="true" \
-            //                         --csv.data-folder="checkmarx" \
-            //                         --app="${CX_PROJECT}" \
-            //                         --cx-team="${CX_TEAM}" \
-            //                         --cx-project="${CX_PROJECT}" \
-            //                         --spring.profiles.active="sast" \
-            //                         --f=. \
-            //                         ${CX_PARAMS}
-            //                         """
-            //                         sh '/app/check_timeout.sh'
-            //                     }
-            //                 }
-            //             }
-            //         }
-            //     }
-            // }
+            stage ('checkmarx-scans') {
+                gitlabCommitStatus(name: "checkmarx-scan-test", connection: gitLabConnection('git-lab-master')) {
+                    withCredentials([usernamePassword(credentialsId: 'checkmarx-ac-account', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
+                        withEnv([
+                        "CHECKMARX_USERNAME=${USERNAME}",
+                        "CHECKMARX_PASSWORD=${PASSWORD}",
+                        "CX_TEAM=CxServer/SP/Company/TLT",
+                        "CX_PROJECT=TAO-TF2",
+                        "CHECKMARX_BASE_URL=https://checkmarx.nvidia.com",
+                        "CHECKMARX_VERSION=9.0",
+                        "CHECKMARX_SETTINGS_OVERRIDE=false",
+                        "CHECKMARX_CONFIGURATION=Default Configuration",
+                        "CHECKMARX_SCAN_PRESET=Checkmarx Default",
+                        "CX_FLOW_BREAK_BUILD=true",
+                        "CX_FLOW_ZIP_EXCLUDE=''",
+                        "CX_PARAMS=''"
+                        ]){
+                            docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
+                                def img = 'pstooling/images/base-images/debian:cxflow-latest-prodsec-stable'
+                                docker.image(img).inside("--entrypoint=''") {
+                                    sh '/app/check_variables.sh jenkins'
+                                    sh """
+                                    java -jar /app/cx-flow.jar \
+                                    --scan \
+                                    --bug-tracker="Csv" \
+                                    --csv.file-name-format="[TEAM]-[PROJECT]-[TIME].csv" \
+                                    --csv.include-headers="true" \
+                                    --csv.data-folder="checkmarx" \
+                                    --app="${CX_PROJECT}" \
+                                    --cx-team="${CX_TEAM}" \
+                                    --cx-project="${CX_PROJECT}" \
+                                    --spring.profiles.active="sast" \
+                                    --f=. \
+                                    ${CX_PARAMS}
+                                    """
+                                    sh '/app/check_timeout.sh'
+                                }
+                            }
+                        }
+                    }
+                }
+            }
 
-            // stage ('pulse_oss_scan') {
-            //     gitlabCommitStatus(name: "pulse_oss_scan", connection: gitLabConnection('git-lab-master')) {
-            //         catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-            //             withEnv(["TAO_VERSION=5.0.0", "IMAGE_NAME=nvcr.io/nvstaging/tao/tao-toolkit-tf2", "TF_VERSION=2.9.1", "CUDA_VERSION=11.8"]){
-            //                 docker.withRegistry('https://nvcr.io', 'NGC_API_KEY'){
-            //                     docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
-            //                         def NSPECT_ID="NSPECT-76DN-OP7I"
-            //                         def SSA_TOKEN=getPulseToken()
-            //                         def CONTAINER_TAG="${IMAGE_NAME}:v${TAO_VERSION}-tf${TF_VERSION}-${BUILD_NUMBER}-dev-cuda${CUDA_VERSION}"
-            //                         def CONTAINER_ARCHIVE="container_image.tar"
-            //                         def CONTAINER_SCAN_POLICY="policy.json"
+            stage ('pulse_oss_scan') {
+                gitlabCommitStatus(name: "pulse_oss_scan", connection: gitLabConnection('git-lab-master')) {
+                    withEnv(["TAO_VERSION=5.0.0", "IMAGE_NAME=nvcr.io/nvstaging/tao/tao-toolkit-tf2", "TF_VERSION=2.9.1", "CUDA_VERSION=11.8"]){
+                        docker.withRegistry('https://nvcr.io', 'NGC_API_KEY'){
+                            docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
+                                def NSPECT_ID="NSPECT-76DN-OP7I"
+                                def SSA_TOKEN=getPulseToken()
+                                def CONTAINER_TAG="${IMAGE_NAME}:v${TAO_VERSION}-tf${TF_VERSION}-${BUILD_NUMBER}-dev-cuda${CUDA_VERSION}"
+                                def CONTAINER_ARCHIVE="container_image.tar"
+                                def CONTAINER_SCAN_POLICY="policy.json"
 
-            //                         try {
-            //                             sh """
-            //                             docker save ${CONTAINER_TAG} > ${CONTAINER_ARCHIVE}
-            //                             wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/policy.json
-            //                             ls -al
-            //                             docker run -v .:/dist -w /dist gitlab-master.nvidia.com:5005/pstooling/pulse-group/pulse-container-scanner/pulse-cli:stable /bin/sh -c "pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN scan -i $CONTAINER_ARCHIVE -p $CONTAINER_SCAN_POLICY -o || true"
-            //                             ls -al
-            //                             cat pulse-cli.log
-            //                             """
-            //                         } catch (Exception e) {
-            //                             echo "Continuing with the pipeline..."
-            //                             echo "An error occurred: ${e.getMessage()}"
-            //                         }
+                                try {
+                                    sh """
+                                    docker save ${CONTAINER_TAG} > ${CONTAINER_ARCHIVE}
+                                    wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/policy.json
+                                    ls -al
+                                    docker run -v .:/dist -w /dist gitlab-master.nvidia.com:5005/pstooling/pulse-group/pulse-container-scanner/pulse-cli:stable /bin/sh -c "pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN scan -i $CONTAINER_ARCHIVE -p $CONTAINER_SCAN_POLICY -o || true"
+                                    ls -al
+                                    cat pulse-cli.log
+                                    """
+                                } catch (Exception e) {
+                                    echo "Continuing with the pipeline..."
+                                    echo "An error occurred: ${e.getMessage()}"
+                                }
 
-            //                         execution_script = '''
-            //                             wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/vulnerabilities_validation.py
-            //                             ls -al
-            //                             python3 -m pip install pandas
-            //                             python3 vulnerabilities_validation.py
-            //                         '''
-            //                         def shellOutput = sh(script: execution_script, returnStdout: true).toString()
-            //                         echo shellOutput
-            //                         if (shellOutput.contains("Scan result : FAIL")) {
-            //                             error("Unsuccessful Execution . . .")
-            //                         }
+                                execution_script = '''
+                                    wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/vulnerabilities_validation.py
+                                    ls -al
+                                    python3 -m pip install pandas
+                                    python3 vulnerabilities_validation.py
+                                '''
+                                def shellOutput = sh(script: execution_script, returnStdout: true).toString()
+                                echo shellOutput
+                                if (shellOutput.contains("Scan result : FAIL")) {
+                                    error("Unsuccessful Execution . . .")
+                                }
 
-            //                         sh "rm -rf ${CONTAINER_ARCHIVE}"
-            //                     }
-            //                 }
-            //             }
-            //         }
-            //     }
-            // }
+                                sh "rm -rf ${CONTAINER_ARCHIVE}"
+                            }
+                        }
+                    }
+                }
+            }
 
             stage ('cleanup_scratch_space_in_dind') {
                 sh 'umount /home/scratch.metropolis2'
diff --git a/Jenkinsfile.release b/Jenkinsfile.release
--- a/Jenkinsfile.release
+++ b/Jenkinsfile.release
@@ -144,6 +144,32 @@ spec:
                 }
             }
 
+            stage ('generate_change_logs') {
+                // Get the current build
+                def currentBuild = currentBuild
+                
+                // Find the last successful build
+                def lastSuccessfulBuild = currentBuild.previousSuccessfulBuild
+                
+                def formattedDate
+                
+                if (lastSuccessfulBuild != null) {
+                    // Get the timestamp of the last successful build
+                    def lastSuccessfulBuildDate = new Date(lastSuccessfulBuild.getTimeInMillis())
+                    
+                    // Format the date to MM/dd/yyyy
+                    formattedDate = lastSuccessfulBuildDate.format("MM/dd/yyyy")
+                } else {
+                    // Default date if no previous successful build is found
+                    formattedDate = "03/29/2024"
+                }
+                
+                // Print the previous successful build date
+                echo "Previous Successful Build Date: ${formattedDate}"
+
+                sh "python3 ci/generate_changelog/generate_changelog.py -d ${formattedDate} -o /home/scratch.metropolis2/users/release_pipeline_files/change_logs/"
+            }
+
             stage ('cleanup_scratch_space') {
                 sh 'umount /home/scratch.metropolis2'
                 sh 'ls -l /home/scratch.metropolis2'
@@ -246,72 +272,44 @@ spec:
 
             stage ('pulse_oss_scan') {
                 gitlabCommitStatus(name: "pulse_oss_scan", connection: gitLabConnection('git-lab-master')) {
-                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
-                        withEnv(["TAO_VERSION=5.2.0", "IMAGE_NAME=nvcr.io/nvstaging/tao/tao-toolkit-tf2", "TF_VERSION=2.9.1", "CUDA_VERSION=11.8"]){
-                            docker.withRegistry('https://nvcr.io', 'NGC_API_KEY'){
-                                docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
-                                    def NSPECT_ID="NSPECT-76DN-OP7I"
-                                    def SSA_TOKEN=getPulseToken()
-                                    def CONTAINER_TAG="${IMAGE_NAME}:v${TAO_VERSION}-tf${TF_VERSION}-${BUILD_NUMBER}-dev-cuda${CUDA_VERSION}"
-                                    def CONTAINER_ARCHIVE="container_image.tar"
-                                    def CONTAINER_SCAN_POLICY="policy.json"
+                    withEnv(["TAO_VERSION=5.2.0", "IMAGE_NAME=nvcr.io/nvstaging/tao/tao-toolkit-tf2", "TF_VERSION=2.9.1", "CUDA_VERSION=11.8"]){
+                        docker.withRegistry('https://nvcr.io', 'NGC_API_KEY'){
+                            docker.withRegistry('https://gitlab-master.nvidia.com:5005', 'jenkins-TLT-pkg') {
+                                def NSPECT_ID="NSPECT-76DN-OP7I"
+                                def SSA_TOKEN=getPulseToken()
+                                def CONTAINER_TAG="${IMAGE_NAME}:v${TAO_VERSION}-tf${TF_VERSION}-${BUILD_NUMBER}-dev-cuda${CUDA_VERSION}"
+                                def CONTAINER_ARCHIVE="container_image.tar"
+                                def CONTAINER_SCAN_POLICY="policy.json"
 
-                                    try {
-                                        sh """
-                                        docker save ${CONTAINER_TAG} > ${CONTAINER_ARCHIVE}
-                                        wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/policy.json
-                                        ls -al
-                                        docker run -v .:/dist -w /dist gitlab-master.nvidia.com:5005/pstooling/pulse-group/pulse-container-scanner/pulse-cli:stable /bin/sh -c "pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN scan -i $CONTAINER_ARCHIVE -p $CONTAINER_SCAN_POLICY -o || true"
-                                        """
-                                    } catch (Exception e) {
-                                        echo "Continuing with the pipeline..."
-                                        echo "An error occurred: ${e.getMessage()}"
-                                    }
-
-                                    execution_script = '''
-                                        wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/vulnerabilities_validation.py
-                                        ls -al
-                                        python3 -m pip install pandas
-                                        python3 vulnerabilities_validation.py
-                                    '''
-                                    def shellOutput = sh(script: execution_script, returnStdout: true).toString()
-                                    echo shellOutput
-                                    if (shellOutput.contains("Scan result : FAIL")) {
-                                        error("Unsuccessful Execution . . .")
-                                    }
-
-                                    sh "rm -rf ${CONTAINER_ARCHIVE}"
+                                try {
+                                    sh """
+                                    docker save ${CONTAINER_TAG} > ${CONTAINER_ARCHIVE}
+                                    wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/policy.json
+                                    ls -al
+                                    docker run -v .:/dist -w /dist gitlab-master.nvidia.com:5005/pstooling/pulse-group/pulse-container-scanner/pulse-cli:stable /bin/sh -c "pulse-cli -n $NSPECT_ID --ssa $SSA_TOKEN scan -i $CONTAINER_ARCHIVE -p $CONTAINER_SCAN_POLICY -o || true"
+                                    """
+                                } catch (Exception e) {
+                                    echo "Continuing with the pipeline..."
+                                    echo "An error occurred: ${e.getMessage()}"
                                 }
+
+                                execution_script = '''
+                                    wget https://raw.githubusercontent.com/achafale/Jenkins-CI/main/vulnerabilities_validation.py
+                                    ls -al
+                                    python3 -m pip install pandas
+                                    python3 vulnerabilities_validation.py
+                                '''
+                                def shellOutput = sh(script: execution_script, returnStdout: true).toString()
+                                echo shellOutput
+                                if (shellOutput.contains("Scan result : FAIL")) {
+                                    error("Unsuccessful Execution . . .")
+                                }
+
+                                sh "rm -rf ${CONTAINER_ARCHIVE}"
                             }
                         }
                     }
                 }
-            }
-
-            stage ('generate_change_logs') {
-                // Get the current build
-                def currentBuild = currentBuild
-                
-                // Find the last successful build
-                def lastSuccessfulBuild = currentBuild.previousSuccessfulBuild
-                
-                def formattedDate
-                
-                if (lastSuccessfulBuild != null) {
-                    // Get the timestamp of the last successful build
-                    def lastSuccessfulBuildDate = new Date(lastSuccessfulBuild.getTimeInMillis())
-                    
-                    // Format the date to MM/dd/yyyy
-                    formattedDate = lastSuccessfulBuildDate.format("MM/dd/yyyy")
-                } else {
-                    // Default date if no previous successful build is found
-                    formattedDate = "03/29/2024"
-                }
-                
-                // Print the previous successful build date
-                echo "Previous Successful Build Date: ${formattedDate}"
-
-                sh "python3 ci/generate_changelog/generate_changelog.py -d ${formattedDate} -o /home/scratch.metropolis2/users/release_pipeline_files/change_logs/"
             }
 
             stage ('cleanup_scratch_space_in_dind') {
